lucas:
  container_name: lucas
  image: postgres:9.6-alpine
  ports:
    - '5432:5432'
  environment:
    POSTGRES_DB: 'lucas_db'
    POSTGRES_USER: 'user'
    POSTGRES_PASSWORD: 'pass'
  ports:
      - "5432:5432"
